name: backend
description: Jokee Single Serving Backend
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bcrypt: ^1.1.3
  dart_frog: ^1.1.0
  dio: ^5.5.0+1
  dotenv: ^4.1.0
  either_dart: ^1.0.0
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  json_annotation: ^4.9.0
  postgres: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - .env
